#!/bin/sh

FEED=content/rust2018/feed.json

echo "Checking for duplicate URLs:"
jq '.items[].url' < "$FEED" | sort | uniq -d

echo
echo "Checking for placeholders:"
rg 'FIXME|null|1970-01-01' "$FEED"

echo
echo "Checking for empty strings:"
rg '"\s*"' "$FEED"
